### ISSUE TITLE
How to run this?

### ISSUE THREAD

**Issue by mrinal18** [quqixun/ADDetection#1]
i read your code and i found it really interesting. although, how do you run the codes and what data have you used?

**Comment by mrinal18** [comment]
And also, how do you classify the images?

**Comment by quqixun** [comment]
Hi, @Mrinal18 , thanks for your interest.
Recently, I don't have time to write some descriptions of this project.
Maybe one week later. Sorry for that.

**Comment by mrinal18** [comment]
@quqixun just kindly guide me how to run it, i'll figure out the rest. Thank you.

**Comment by DXP0926** [comment]
Hei, can you provide the dataset for training and testing?
