### ISSUE TITLE
Hi, can you provide the data for training and testing?

### ISSUE THREAD

**Issue by DXP0926** [quqixun/ADDetection#2]

**Comment by quqixun** [comment]
The dataset used in this project is a part of ADNI.
You can find all subject IDs in src/DataSplit.
BTW, all images have been pre-processed by FreeSurfer.
You may search and download images from ADNI.

**Comment by DXP0926** [comment]
Sorry to bother you but I can't find the specific dataset, can't you put the set on drive or on wetransfer, I am trying to understand the program but I can't without a dataset

**Comment by quqixun** [comment]
I may not upload dataset to any cloud drive.
You should access dataset at ADNI [more information](http://adni.loni.usc.edu/data-samples/access-data/).
Sorry for that.
