### ISSUE TITLE
under the data/adni_subj/AD/002_S_0619 file ,there are  four files named 0,1,2,3. 

### ISSUE THREAD

**Issue by yxyyr** [quqixun/ADDetection#3]
under the data/adni_subj/AD/002_S_0619 file ,there are  four files named 0,1,2,3. what's mean of these files?

**Comment by quqixun** [comment]
> under the data/adni_subj/AD/002_S_0619 file ,there are four files named 0,1,2,3. what's mean of these files?

Sorry for so so so late reply.
0, 1, 2, 3 are for different modal of MRI, they are T1, T2. T1-CE and T2-Flair.
